### ISSUE TITLE
Suggestion: Either a list of all cultures within a nation or a "dominant culture" statistic on the nation board. 

### ISSUE THREAD

**Issue by T3mp0st** [TownyAdvanced/TownyCultures#2]
"A different list of this nature, which I would support, is a 'nation-based' list, where you could get a list of all component cultures in a particular nation. This would be a useful geopolitical tool to assess the loyalties of a particular friend or foe. Feel free to create a new ticket for that." 
this was mentioned in my previous feature request and is something i would most certainly like to see added, however when reading this it does raise the question of whether culture should instead of being on a town basis, be on the basis of individuals. The idea of having a diaspora inside a nation seems less realistic if you are expecting a multicultural empire to be made up of extremely homogeneous town blocks of each culture. I'm not sure how realistic it is to attach culture to the resident file in towny, but I think it would lead to a more natural system from top to bottom. If that isn't realistic, a list of cultures within a nation, or at the very least a "dominant culture" indicator would be a welcome addition

**Comment by Goosius1** [comment]
- Hi. Yes the list of cultures within a nation should do do-able. On the nation screen, I'm envisaging it might look something like this :
```
Nation:  Blahname
Bank: etc.
Towns:  <List of towns>
Culture:  Celtic 60%,Greek 36%, Roman 4%
```

- On the idea of culture being set on the level of residents, this is also a valid idea. Certainly it is more realistic, however, I fear that it would be a bit "too much" complexity for most Towny servers. 
   - Since each player would have to switch their own culture, many, not knowing how the feature works, might just not do it at all, leading to less coverage than the town-based approach.
   - Those that did switch might not really understand the culture they sign up to, and might want to take it in a different direction (and remember that there is no entry requirement for joining a culture), thus cultures might become so disorganized that they would simply not become important aspect of the gameworld.
   - In contrast, the town-based approach allows a smaller and more knowledgeable group (Mayors) to more cohesively co-ordinate each culture in terms of events, customs, and architecture, giving (I think), a better chance for culture to become an important aspect of the the gameworld.
